version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'sunday'
    commit-message:
      prefix: "chore(deps): "
    open-pull-requests-limit: 10
